config/routes.rb
Govindata::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      namespace :services do
        namespace :iphone do
          resources :basic do
            collection do
              post "signup"
              post "authenticate"
              post "get_datasets"
              post "remove_datasets"
              post "update_settings"
            end
          end
          resources :sync do
            collection do
              get "/:action"
            end
          end
        end
      end
    end
  end

  get "/iphone_app_users" => "welcome#users", :as => :app_users
  get "/reset_password" => "welcome#reset_password"

  authenticated :user do
    root :to => 'welcome#index'
  end
  
  devise_for :users do
    root to: "devise/sessions#new"
  end

    root :to => 'welcome#index'
  resources :datasets

  post "/welcome/upload" => "welcome#upload"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/dataset.rb
class Dataset
  require 'fileutils'
  # require 'iconv'

  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :description, type: String
  field :model_classname, type: String
  field :model_filename, type: String
  field :model_attrs
  field :user_count
  field :keywords

  validates :title, presence: true 

  # attr_accessible :user_count, :id

  has_and_belongs_to_many :users

  # scope :recently_viewed
  scope :most_popular, lambda{|x=5| desc(:user_count).limit(x)}
  scope :newly_added, lambda{|x=5| desc(:created_at).limit(x)}

  def self.update_user_count
    all.each do |d|
      d.update_attribute(:user_count, d.users.count)
    end
  end

  def init_model
    unless File.exists?(full_model_filename)
      puts "-----------"+full_model_filename.inspect+"-----------"
      Dataset.create_model model_classname, model_attrs, model_filename.gsub(".rb", "") #because .rb will be added when creating the model
    end
    puts model_classname.inspect
    puts full_model_filename.inspect
    my_klass        = Object.const_set(model_classname, Class.new)
    my_klass.class_eval File.open(full_model_filename).read.gsub("class #{model_classname}\n", '').gsub("end       \n", "") #initializing the model for use
    eval(model_classname)
  end

  def full_model_filename
    # Rails.root + "app/models/" + model_filename
    Rails.root.join('app', 'models', model_filename)
  end

  def content
    humanize_content(
      init_model.all.as_json(
          :except => [:created_at, :updated_at, :_id],
        )
      )  #rescue []
  end

  def humanize_content target_json
    target_json.collect do |obj|
      hsh = Hash.new
      obj.each do |key, val|
        hsh[key.humanize] = val
      end
      hsh
    end
    # hash.inject({}){|new_hash, key_value|
    #   key, value = key_value
    #   raise key_value.inspect
    #   new_hash[key.humanize] = value
    #   new_hash
    # }
  end

  def self.save_data_model params
    nu_model_name   = params[:source_file].original_filename.split(".")[0].downcase.underscore rescue nil
    class_name      = nu_model_name.classify rescue nil
    result          = nil 

    filetype        = params[:source_file].original_filename.split(".").last rescue nil
    if filetype == "xls"
      result        = read_excel params, nu_model_name, class_name
    elsif filetype == "csv"
      result        = read_csv params, nu_model_name, class_name
    end
    return {:status => "failed"} unless result
    if result[:status] == "success"
      return {
        :status => "success", 
        :dataset => {
          :title => params[:dataset][:title].blank? ? params[:source_file].original_filename.split(".")[0].titleize : params[:dataset][:title] , 
          :description => params[:dataset][:description],  
          :keywords => params[:dataset][:keywords],  
          :model_classname => class_name, :model_filename => nu_model_name+".rb",
          :model_attrs => result[:model_attrs]
          }
        }
    else
      return result
    end
  end

  def self.read_excel params, nu_model_name, class_name
    Spreadsheet.client_encoding = 'UTF-8'
    book    = Spreadsheet.open params[:source_file].tempfile.path
    sheet1  = book.worksheet 0
    # raise sheet1.row(0).formatted.inspect

    # model_attrs = sheet1.row(0).formatted.collect{|x| x.downcase.gsub("&","n").gsub(".","").gsub(" ","_").underscore.to_sym}
    @model_attrs     = sheet1.row(0).formatted.collect{|x| (x.gsub("%","percent").gsub("&","n").gsub(".","").parameterize.underscore rescue nil)}.compact
    @model_attrs     = @model_attrs.collect{|x| x.match(/^[0-9]/).present? ? "_#{x}".to_sym : x.to_sym }

    # model_attrs.shift #removing first element

    create_model(class_name, @model_attrs, nu_model_name)
    # Uploading file contents
    sheet1.each 1 do |row|
      obj_attrs = Hash.new
      0.upto sheet1.last_row_index do |index|
        ## model_attrs[index-1] coz we have already pushed the first element outta model_attrs
        # obj_attrs.merge!({model_attrs[index-1].to_sym => row[index]}) rescue nil
        obj_attrs.merge!({@model_attrs[index].to_sym => row[index]}) rescue nil
      end
      # Dont save if the row is empty
      @new_obj = eval(class_name).create!(obj_attrs) unless obj_attrs.values.compact.size == 0
    end
    return {:status => "success", :model_attrs => @model_attrs}
  end

  def self.read_csv params, nu_model_name, class_name
   csv  = SmarterCSV.process(params[:source_file].tempfile.path, :file_encoding => 'windows-1251:utf-8')
    if File.exists?(Rails.root + "app/models/#{nu_model_name}.rb")
      eval(class_name).destroy_all
    else
      # raise csv.first.keys.collect{|x|x.to_s.parameterize.underscore.squeeze("_")}.inspect
      @model_attrs = csv.first.keys.collect{|x|x.to_s.parameterize.underscore.squeeze("_")}
      create_model(class_name, @model_attrs, nu_model_name)
    end
    csv.each do |row|
      eval(class_name).create!(Hash[row.map{|k,v| [k.to_s.parameterize.underscore.squeeze("_"), v]}]) 
    end
    return {:status => "success", :model_attrs => @model_attrs }
  end

  def self.create_model class_name, model_attrs, nu_model_name
    # Creating a model file for requested model
    # File.open(Rails.root + "app/models/#{nu_model_name}.rb", "w"){|f| f.write(
    File.open(Rails.root + Rails.root.join('app', 'models', (nu_model_name+".rb")), "w"){|f| f.write(
<<-CODE
class #{class_name}
  include Mongoid::Document
  # include Mongoid::Timestamps

  #{model_attrs.collect{|attribute| "field :#{attribute}"}.join("\n\t")}
end       
CODE
    )}
    # Using the above created model file to initialize the model (Source : http://stackoverflow.com/questions/11764921/mongoid-creating-runtime-models-for-embedding)
    model_filename  = "#{Rails.root}/app/models/#{nu_model_name}.rb"
    my_klass        = Object.const_set(class_name, Class.new)
    # raise File.open(model_filename).read.gsub("class #{class_name}\n", '').gsub("end       \n", "").inspect
    my_klass.class_eval File.open(model_filename).read.gsub("class #{class_name}\n", '').gsub("end       \n", "") #initializing the model for use
  end

end


















 # # Processing CSV in chunks
 #  def self.read_csv params, nu_model_name, class_name
 #    # csv_text = File.read(params[:source_file].tempfile.path).encode!('UTF-8', 'UTF-8', :invalid => :replace)
 #    # csv    = CSV.parse(csv_text, :headers => true)
 #    csv_chunks  = SmarterCSV.process(params[:source_file].tempfile.path, {:chunk_size => 100, :file_encoding => 'windows-1251:utf-8'})
 #    if File.exists?(Rails.root + "app/models/#{nu_model_name}.rb")
 #      eval(class_name).destroy_all
 #    else
 #      model_attrs = csv_chunks.first.first.keys.collect{|x|x.to_s}
 #      create_model(class_name, model_attrs, nu_model_name)
 #    end
 #    csv_chunks.each do |chunk|
 #      # we're passing a block in, to process each resulting hash / row (block takes array of hashes)
 #      # when chunking is enabled, there are up to :chunk_size hashes in each chunk
 #      eval(class_name).collection.insert( chunk )   # insert up to 100 records at a time
 #    end
 #    return {:status => "success"}
 #  end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_filter :authenticate_user!
  protect_from_forgery

  def index
    @datasets = Dataset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datasets }
    end
  end

  def show
    @dataset = Dataset.find(params[:id])
    @dataset.init_model

    respond_to do |format|
      format.html # show.html.erb
      # format.json { render json: @dataset.as_json(:methods => Dataset.content ) }
      format.json { render json: @dataset.to_json(:methods => :content ) }
    end
  end

  def new
    @dataset = Dataset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dataset }
    end
  end

  def edit
    @no_upload  = true
    @dataset    = Dataset.find(params[:id])
  end

  def create
    respond_to do |format|
      result = Hash.new
      # begin
        result = Dataset.save_data_model params
      # rescue Exception => e
      #   puts e.inspect
      # end
      if result[:status] == "success"
        dataset_exists = Dataset.find_by(title: result[:dataset][:title]).present? rescue nil
        unless dataset_exists
          puts result[:dataset].inspect
          @dataset = Dataset.new(result[:dataset])
          puts @dataset.inspect
          @dataset.save!
        else
          @dataset = Dataset.find_by(title: result[:dataset][:title])
        end
        format.html { redirect_to @dataset, notice: 'Dataset was successfully created.' }
      else
        @dataset = Dataset.new(params[:dataset])
        flash[:error] = 'There was some problem saving this dataset. Please verify the Source File & its contents. (Allowed extensions .xls | .csv)'
        format.html { render action: "new" }
      end
    end
  end

  def update
    @dataset    = Dataset.find(params[:id])
    @no_upload  = true

    respond_to do |format|
      if @dataset.update_attributes(params[:dataset])
        format.html { redirect_to @dataset, notice: 'Dataset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dataset = Dataset.find(params[:id])
    model_full_filename = Rails.root + "app/models/" + @dataset.model_filename
    # raise File.exists?(model_full_filename).inspect
    eval(@dataset.model_classname).destroy_all
    File.delete(model_full_filename) #if File.exists?(model_full_filename)
    @dataset.destroy
    redirect_to datasets_url, notice: "Dataset was destroyed successfully."
  end
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/views/datasets/_form.html.erb
<%= form_for @dataset , :html => {:multipart => true} do |f| %>
  <% if @dataset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dataset.errors.count, "error") %> prohibited this dataset from being saved:</h2>
      <ul>
      <% @dataset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- <div class="element">
    <label for="comments">Comments</label>
    <input type="radio" name="comments" value="on" checked="checked" />
    Enabled
    <input type="radio" name="comments" value="off" />
    Disabled
  </div> -->
  <% unless @no_upload.present? %>
  <div class="element">
    <label for="attach">
      Dataset Source file 
      <span class="red">(required)</span>
      <span>(Allowed extensions .xls | .csv)</span>
      <!-- <span>(Max allowed file size 1mb)</span> -->
    </label>
    <%= file_field_tag :source_file %>
  </div>
  <% end %>
  <div class="element">
    <label for="name">
      Dataset title
      <span>(Optional) If left blank, title will automatically be selected based on source file</span>
    </label>
    <%= f.text_field :title, :class => "text" %>
  </div>
  <div class="element">
    <label for="content">
      Description
      <span>(Describe about the dataset in a few words)</span>
    </label>
    <%= f.text_area :description, :rows => 5, :class => "textarea" %>
    <!-- <textarea name="content" class="textarea" rows="10"></textarea> -->
  </div>
  <div class="element">
    <label for="category">
      Keywords
    </label>
    <%= f.text_field :keywords, :class => "text" %>
  </div>
  <div class="entry">
    <!-- <button type="submit">Preview</button> -->
    <button type="submit" class="add">Save Dataset</button>
    <%= link_to "Cancel", datasets_path, :class => "button cancel" %>
    <!-- <button class="cancel">Cancel</button> -->
  </div>
<% end %>

app/views/datasets/edit.html.erb
<%= render "/commons/error_messages" %>
<div class="full_w">
	<div class="h_title">Add new Dataset</div>
	<%= render 'form' %>
</div>

app/views/datasets/index.html.erb
<%= render "/commons/error_messages" %>
<div class="full_w">
  <div class="h_title">Manage Datasets</div>
  <h2>Listing datasets</h2>
  <p>
    List of all the datasets imported from Government fo India Data Portal. Import a new dataset using the <b>"Add New Dataset"</b> button provided below. <br>
    <b>Note : </b>Please a add a relevant description to the dataset so that the users viewing the data can know more about the dataset.
  </p>

  <div class="entry">
    <div class="sep"></div>
  </div>
  <table id="datasets">
    <thead>
      <tr>
        <!-- <th scope="col">ID</th> -->
        <th scope="col">Title</th>
        <!-- <th scope="col">Author</th> -->
        <th scope="col">Keywords</th>
        <th scope="col">Created On</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @datasets.each do |dataset| %>
      <tr>
        <!-- <td class="align-center">1</td> -->
        <td><%= (link_to dataset.title.titleize, dataset_path(dataset)) rescue nil %></td>
        <!-- <td>Admin</td> -->
        <td><%= truncate(dataset.keywords, length: 30, omission: "...") %></td>
        <td><%= dataset.created_at %></td>
        <td style="width:65px;">
          <%= link_to "", dataset_path(dataset), :class => "table-icon view" %>
          <%= link_to "", edit_dataset_path(dataset), :class => "table-icon edit" %>
          <%= link_to '', dataset_path(dataset), :confirm => 'Are you sure?', :method => :delete, :class => "table-icon delete" %>
          <!-- <a href="#" class="table-icon archive" title="Archive"></a> -->
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="entry">
    <!-- <div class="pagination">
      <span>« First</span>
      <span class="active">1</span>
      <a href="">2</a>
      <a href="">3</a>
      <a href="">4</a>
      <span>...</span>
      <a href="">23</a>
      <a href="">24</a>
      <a href="">Last »</a>
    </div> -->
    <div class="sep"></div>
    <%= link_to 'Add New Dataset', new_dataset_path, :class => "button add" %>
    <a class="button" href="/">Home</a>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function(){
  $("#datasets").dataTable({
    "sPaginationType": "full_numbers",
    "bJQueryUI": true
  });
});
</script>

app/views/datasets/new.html.erb
<%= render "/commons/error_messages" %>
<div class="full_w">
	<div class="h_title">Add new Dataset</div>
	<!-- <h2>Listing datasets</h2> -->
	<p>
		<b>Note :</b> You can download dataset source files from <%= link_to "Govt of India Data Portal", 'http://data.gov.in/catalogs/', :include => "_blank" %>
	</p>

	<!-- <b>Note : </b>Please a add a relevant description to the dataset so that the users viewing the data can know more about the dataset.
	</p> -->

	<%= render 'form' %>
</div>

app/views/datasets/show.html.erb
<%= render "/commons/error_messages" %>
<div class="full_w">
	<div class="h_title">Dataset Details</div>
	<h2><%= @dataset.title.titleize %></h2>
	<p><%= @dataset.description || "No description available for this dataset" %></p>
	<p> <b>Keywords : </b><%= @dataset.keywords || "No keywords found" %></p>

	<div class="entry">
		<div class="sep"></div>
	</div>
	<table id="dataset_content" class="display">
		<thead>
			<tr>
				<% eval(@dataset.model_classname).new.attribute_names[1..-1].each do |attrb| %>
				<th scope="col">
					<%= attrb.humanize %></th>
				<% end %></tr>
		</thead>
		<tbody>
			<%# eval(@dataset.model_classname).all[1..-1].each do |datarow| %>
			<% eval(@dataset.model_classname).all.each do |datarow| %>
			<tr>
				<% eval(@dataset.model_classname).new.attribute_names[1..-1].each do |attrb| %>
				<td><%= datarow.instance_eval(attrb) %></td>
				<% end %>
			</tr>
			<% end %>
		</tbody>
	</table>
	<div style="clear:both"></div>
	<div class="sep"></div>
	<div class="entry">
		<%= link_to "Delete", dataset_path(@dataset), :confirm => 'Are you sure?', :method => :delete,  :class => "button delete" %>
		<%= link_to 'Add New Dataset', new_dataset_path, :class => "button add" %>
		<%= link_to "Datasets List", datasets_path, :class => "button" %>
		<!-- <a class="button" href="">Categories</a> -->
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$("#dataset_content").dataTable({
		"sPaginationType": "full_numbers",
		"bJQueryUI": true
	});
});
</script>