config/routes.rb
Govindata::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      namespace :services do
        namespace :iphone do
          resources :basic do
            collection do
              post "signup"
              post "authenticate"
              post "get_datasets"
              post "remove_datasets"
              post "update_settings"
            end
          end
          resources :sync do
            collection do
              get "/:action"
            end
          end
        end
      end
    end
  end

  get "/iphone_app_users" => "welcome#users", :as => :app_users
  get "/reset_password" => "welcome#reset_password"

  authenticated :user do
    root :to => 'welcome#index'
  end
  
  devise_for :users do
    root to: "devise/sessions#new"
  end

    root :to => 'welcome#index'
  resources :datasets

  post "/welcome/upload" => "welcome#upload"

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="Amit Jangu" />
	<title>knowIN (knowing my India) - Admin</title>
	<%#= stylesheet_link_tag    "application", :media => "all" %>
	<%#= javascript_include_tag "application" %>
	<link rel="stylesheet" type="text/css" href="/assets/application.css" media="screen" />
	<script src="/assets/application.js" type="text/javascript"></script>
	
	<%= csrf_meta_tags %>
	<link rel="stylesheet" type="text/css" href="/assets/style.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="/assets/navi.css" media="screen" />
	<!--<script type="text/javascript" src="/assets/jquery-1.7.2.min.js"></script>-->
	<script type="text/javascript">
		$(function(){
			$(".box .h_title").not(this).next("ul").hide("normal");
			$(".box .h_title").not(this).next("#home").show("normal");
			$(".box").children(".h_title").click( function() { $(this).next("ul").slideToggle(); });
		});
	</script>
</head>
<body>
	<div class="wrap">
		<div id="header">
			<div id="top">
				<div class="left">
					<p>
						Welcome, <strong><%= current_user.username.titleize rescue nil %></strong>
						[ <%= link_to("Logout", destroy_user_session_path, :method => :delete) %> ]
					</p>
				</div>
				<div class="right">
					<div class="align-right">
						<p>
							<!-- Last login: <strong>23-04-2012 23:12</strong> -->
							Last login: <strong><%= time_ago_in_words current_user.last_sign_in_at %> ago</strong>
						</p>
					</div>
				</div>
			</div>
			<div id="nav">
				<ul>
					<li class="upp">
						<a href="#">Main control</a>
						<ul>
							<li>
								&#8250;
								<a href="/">Home</a>
							</li>
							<!-- <li>
								&#8250;
								<a href="">Reports</a>
							</li> -->
							<li>
								&#8250;
								<%= link_to "Add new Dataset", new_dataset_path %>
							</li>
							<!-- <li>
								&#8250;
								<a href="">Site config</a>
							</li> -->
						</ul>
					</li>
					<li class="upp">
						<a href="#">Manage content</a>
						<ul>
							<li>
								&#8250;
								<%= link_to "Show all datasets", datasets_path %>
							</li>
							<li>
								&#8250;
								<%= link_to "Add new Dataset", new_dataset_path %>
							</li>
							<!-- <li>
								&#8250;
								<a href="">Add new gallery</a>
							</li> -->
							<li>
								&#8250;
								<a href="">Categories</a>
							</li>
						</ul>
					</li>
					<li class="upp">
						<a href="#">Users</a>
						<ul>
							<li>
								&#8250;
								<%= link_to "Show all users", app_users_path %>
							</li>
							<!-- <li>
								&#8250;
								<a href="">Add new user</a>
							</li>
							<li>
								&#8250;
								<a href="">Lock users</a>
							</li> -->
						</ul>
					</li>
					<li class="upp">
						<a href="#">Settings</a>
						<ul>
							<li>
								&#8250;
								<a href="">Change Password</a>
							</li>
							<li>
								&#8250;
								<a href="">Site Configuration</a>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>

		<div id="content">
			<div id="sidebar">
				<div class="box">
					<div class="h_title">&#8250; Main control</div>
					<ul id="home">
						<li class="b1">
							<a class="icon view_page" href="/">Home</a>
						</li>
						<!-- <li class="b2">
							<a class="icon report" href="">Reports</a>
						</li> -->
						<li class="b2">
							<%= link_to "Add new Dataset", new_dataset_path, :class => "icon add_page" %>
						</li>
						<!-- <li class="b1">
							<a class="icon config" href="">Site config</a>
						</li> -->
					</ul>
				</div>

				<div class="box">
					<div class="h_title">&#8250; Manage content</div>
					<ul>
						<li class="b1">
							<%= link_to "Show all datasets", datasets_path, :class => "icon page" %>
						</li>
						<li class="b2">
							<%= link_to "Add new Dataset", new_dataset_path, :class => "icon add_page" %>
						</li>
						<!-- <li class="b1">
							<a class="icon photo" href="">Add new gallery</a>
						</li> -->
						<li class="b2">
							<a class="icon category" href="">Categories</a>
						</li>
					</ul>
				</div>
				<div class="box">
					<div class="h_title">&#8250; Users</div>
					<ul>
						<li class="b1">
							<!-- <a class="icon users" href="">Show all users</a> -->
							<%= link_to "Show all users", app_users_path, :class => "icon users" %>
						</li>
						<!-- <li class="b2">
							<a class="icon add_user" href="">Add new user</a>
						</li>
						<li class="b1">
							<a class="icon block_users" href="">Lock users</a>
						</li> -->
					</ul>
				</div>
				<div class="box">
					<div class="h_title">&#8250; Settings</div>
					<ul>
						<li class="b1">
							<a class="icon block_users" href="">Change Password</a>
						</li>
						<li class="b2">
							<a class="icon config" href="">Site configuration</a>
						</li>
						<!-- <li class="b2">
							<a class="icon contact" href="">Site configuration</a>
						</li> -->
					</ul>
				</div>
			</div>
			<div id="main">
				<%= yield %>
			</div>
			<div class="clear"></div>
		</div>

		<div id="footer">
			<div class="left">
				<p>
					Copyright
					<a href="http://data.gov.in/appschallenge" target="_blank">OpenDataApps</a> 2013
					| Admin Panel :
					<a href="<%= root_url %>">knowIN (knowing my India)</a>
				</p>
			</div>
			<!-- <div class="right">
				<p>
					<a href="">Example link 1</a>
					|
					<a href="">Example link 2</a>
				</p>
			</div> -->
		</div>
	</div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<!-- <meta name="author" content="Paweł 'kilab' Balicki - kilab.pl" /> -->
<title>knowIN (knowing India) - Admin</title>
<link rel="stylesheet" type="text/css" href="/assets/login.css" media="screen" />
</head>
<body>
<div class="wrap">
	<div id="content">
		<div id="main">
			<div class="full_w">
				<%= yield %>
			</div>
			<div class="footer"><a href="">knowIn (Knowing India)</a> | Admin Panel</div>
		</div>
	</div>
</div>

</body>
</html>